# Generated by Django 5.1.1 on 2024-09-26 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feed',
            name='author',
            field=models.CharField(default='squar3', max_length=16),
        ),
    ]
