# Generated by Django 5.1.1 on 2024-10-15 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_feed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='squar3', max_length=16)),
                ('title', models.CharField(default='', max_length=64)),
                ('content', models.TextField(default='')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-creation_time',),
            },
        ),
    ]
