# Generated by Django 5.1.1 on 2024-10-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_writeup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='id',
        ),
        migrations.AddField(
            model_name='writeup',
            name='wid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
