# Generated by Django 5.1.1 on 2024-10-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_writeup_id_writeup_wid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='wid',
        ),
        migrations.AddField(
            model_name='writeup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
