# Generated by Django 5.1.1 on 2024-10-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_writeup_author_remove_writeup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='content',
        ),
        migrations.AddField(
            model_name='writeup',
            name='page_path',
            field=models.CharField(default='', max_length=128),
        ),
    ]
